"""Database module for trade system."""

from trade_system.infrastructure.database.connection import get_db_session, init_db, get_db_context
from trade_system.infrastructure.database.models import (
    TopGainersSnapshot,
    TopGainersStock,
    FOSelectionSnapshot,
    FOSelectionStock,
    FOTopStocksSnapshot,
    FOTopStock,
    SectorPerformanceSnapshot,
    SectorPerformanceSector,
    SectorPerformanceStock,
)
from trade_system.infrastructure.database.repository import (
    save_top_gainers,
    get_top_gainers,
    get_top_gainers_history,
    save_fo_selection,
    get_fo_selection,
    get_fo_selection_history,
    save_fo_top_stocks,
    get_fo_top_stocks,
    get_fo_top_stocks_history,
    save_sector_performance,
    get_sector_performance,
    get_sector_performance_history,
    log_agent_thought,
    get_latest_thoughts,
)

__all__ = [
    "get_db_session",
    "init_db",
    "get_db_context",
    "TopGainersSnapshot",
    "TopGainersStock",
    "FOSelectionSnapshot",
    "FOSelectionStock",
    "FOTopStocksSnapshot",
    "FOTopStock",
    "SectorPerformanceSnapshot",
    "SectorPerformanceSector",
    "SectorPerformanceStock",
    "save_top_gainers",
    "get_top_gainers",
    "get_top_gainers_history",
    "save_fo_selection",
    "get_fo_selection",
    "get_fo_selection_history",
    "save_fo_top_stocks",
    "get_fo_top_stocks",
    "get_fo_top_stocks_history",
    "save_sector_performance",
    "get_sector_performance",
    "get_sector_performance_history",
    "log_agent_thought",
    "get_latest_thoughts",
]
