import logging
from datetime import datetime, timedelta, date
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Any, List
from dataclasses import dataclass

from trade_system.infrastructure.brokers.legacy.fyers import FyersBrokerClient
from trade_system.infrastructure.data.nse_universe import NSE_UNIVERSE
from trade_system.infrastructure.notifications.telegram import TelegramNotifier
from trade_system.config import Settings

LOGGER = logging.getLogger(__name__)

@dataclass
class WeeklyGainer:
    symbol: str
    name: str
    last_close: float
    current_close: float
    change_pct: float

class NSEWeeklyGainersFetcher:
    """Fetcher for Top 10 Weekly Gainers from NIFTY 500."""

    def __init__(self, broker: FyersBrokerClient):
        self.broker = broker
        self.settings = Settings.load()
        self.notifier = TelegramNotifier(
            self.settings.top_gainer_telegram.bot_token or self.settings.telegram.bot_token,
            self.settings.top_gainer_telegram.chat_id or self.settings.telegram.chat_id
        )

    def fetch_weekly_gainers(self, symbols: List[str] = None) -> List[WeeklyGainer]:
        universe = symbols if symbols is not None else NSE_UNIVERSE
        now = datetime.now()
        from_date = (now - timedelta(days=15)).strftime('%Y-%m-%d')
        to_date = now.strftime('%Y-%m-%d')

        gainers: List[WeeklyGainer] = []
        
        LOGGER.info(f"Fetching weekly data for {len(universe)} symbols...")
        
        def fetch_symbol(sym: str) -> WeeklyGainer | None:
            try:
                df = self.broker.get_historical_data(sym, "1W", from_date, to_date)
                if df is not None and len(df) >= 2:
                    # Sort by timestamp to ensure chronological order
                    df = df.sort_values(by="timestamp").reset_index(drop=True)
                    prev_week = df.iloc[-2]
                    curr_week = df.iloc[-1]
                    
                    last_close = float(prev_week['close'])
                    current_close = float(curr_week['close'])
                    
                    if last_close > 0:
                        change_pct = ((current_close - last_close) / last_close) * 100
                        return WeeklyGainer(
                            symbol=sym,
                            name=sym.replace("NSE:", "").replace("-EQ", ""),
                            last_close=last_close,
                            current_close=current_close,
                            change_pct=change_pct
                        )
            except Exception as e:
                pass
            return None

        # Fetch concurrently
        with ThreadPoolExecutor(max_workers=10) as executor:
            futures = {executor.submit(fetch_symbol, sym): sym for sym in universe}
            for future in as_completed(futures):
                res = future.result()
                if res is not None:
                    gainers.append(res)
                    
        return sorted(gainers, key=lambda x: x.change_pct, reverse=True)

    def send_telegram_report(self, gainers: List[WeeklyGainer], top_n: int = 10) -> bool:
        if not gainers:
            return False
            
        top_gainers = gainers[:top_n]
        today_str = date.today().strftime("%d %b %Y")
        lines = [
            f"📅 <b>Nifty 500 Weekly Top {top_n} Gainers</b> ({today_str})",
            "<i>Performance compared to last Friday's close</i>",
            ""
        ]
        
        for rank, stock in enumerate(top_gainers, 1):
            lines.append(f"{rank:02d}. <b>{stock.name}</b>  ₹{stock.current_close:.2f}  (<code>{stock.change_pct:+.2f}%</code>)")
            
        lines.append("\n<i>Generated by AI Post-Market Agent</i>")
        return self.notifier.send("\n".join(lines))
