#!/usr/bin/env python3
"""
Backtest Engine for Dynamic Option Chain Data Change Forensics.

Evaluates signals generated by OptionChainMonitorAgent:
- Max Pain Upward / Downward Migration
- Institutional Writer Traps (Bull Trap, Bear Trap)
- Short Squeezes & Long Liquidations

Uses historical multi-snapshot intraday datasets from data/option_chain_data/
and spot price history from data/trade_system.db.
"""
from __future__ import annotations

import argparse
import glob
import json
import logging
import os
import sqlite3
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from tabulate import tabulate

# Add project root to sys.path
root_dir = Path(__file__).resolve().parents[1]
if str(root_dir / "src") not in sys.path:
    sys.path.insert(0, str(root_dir / "src"))

from trade_system.domains.advisory.application.agent.option_chain_monitor_agent import (
    OptionChainMonitorAgent,
    DynamicForensicResult,
)
from trade_system.shared.config import Settings

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
LOGGER = logging.getLogger("backtest_oc_delta")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Backtest Option Chain Data Change Forensics")
    parser.add_argument(
        "--symbol",
        type=str,
        default="NSE:NIFTY50-INDEX",
        help="Symbol to backtest (e.g. NSE:NIFTY50-INDEX, NSE:NIFTYBANK-INDEX)",
    )
    parser.add_argument(
        "--max-files",
        type=int,
        default=20,
        help="Max snapshot CSV files to process",
    )
    parser.add_argument(
        "--output-file",
        type=str,
        default="data/backtest_option_chain_results.json",
        help="Output path for backtest results",
    )
    return parser.parse_args()


def load_spot_history(db_path: Path, symbol: str) -> pd.DataFrame:
    """Load 15-minute spot price candles from SQLite."""
    conn = sqlite3.connect(db_path)
    query = """
        SELECT timestamp, open, high, low, close, volume 
        FROM ohlcv_15m 
        WHERE symbol = ? 
        ORDER BY timestamp ASC
    """
    df = pd.read_sql_query(query, conn, params=(symbol,))
    conn.close()
    if not df.empty:
        df["timestamp"] = pd.to_datetime(df["timestamp"], format="mixed")
        df.sort_values("timestamp", inplace=True)
    return df


def get_spot_at_time(
    spot_df: pd.DataFrame,
    target_dt: datetime,
    oc_snap: Optional[pd.DataFrame] = None,
) -> float:
    """Find spot price at or slightly before target_dt, or fallback to synthetic parity."""
    if not spot_df.empty:
        prior_candles = spot_df[spot_df["timestamp"] <= target_dt]
        if not prior_candles.empty:
            return float(prior_candles["close"].iloc[-1])
        # If before first candle, check exact future candle within 15 min
        future_candles = spot_df[spot_df["timestamp"] >= target_dt]
        if not future_candles.empty:
            diff = (future_candles["timestamp"].iloc[0] - target_dt).total_seconds()
            if diff <= 900:
                return float(future_candles["open"].iloc[0])

    # Fallback to synthetic spot from option chain put-call parity: S ~= K + C - P
    if oc_snap is not None and not oc_snap.empty:
        ce = oc_snap[oc_snap["option_type"] == "CE"].set_index("strike")["ltp"]
        pe = oc_snap[oc_snap["option_type"] == "PE"].set_index("strike")["ltp"]
        common = ce.index.intersection(pe.index)
        if not common.empty:
            diff = (ce.loc[common] - pe.loc[common]).abs()
            atm = diff.idxmin()
            c_val = float(ce.loc[atm])
            p_val = float(pe.loc[atm])
            if c_val > 0 or p_val > 0:
                return float(atm + c_val - p_val)

    return 0.0


def run_backtest(symbol: str, max_files: int = 20) -> Dict[str, Any]:
    settings = Settings.load()
    db_path = settings.data_dir / "trade_system.db"
    clean_sym = symbol.replace("NSE:", "").replace("BSE:", "").replace("-INDEX", "")

    LOGGER.info("Loading spot price database for %s...", symbol)
    spot_df = load_spot_history(db_path, symbol)
    LOGGER.info("Loaded %d spot candles from database.", len(spot_df))

    # Find snapshot CSVs
    pattern = str(settings.option_chain_data_dir / f"{clean_sym}_strikes_*.csv")
    csv_files = sorted(glob.glob(pattern))
    if not csv_files:
        LOGGER.error("No option chain strike files found matching: %s", pattern)
        return {}

    selected_files = csv_files[-max_files:]
    LOGGER.info("Found %d strike files. Backtesting across latest %d files...", len(csv_files), len(selected_files))

    agent = OptionChainMonitorAgent(
        settings=settings,
        enable_telegram=False,
    )

    trades: List[Dict[str, Any]] = []

    for file_path in selected_files:
        date_str = Path(file_path).stem.split("_")[-1]
        LOGGER.info("Processing session %s (%s)...", date_str, Path(file_path).name)

        try:
            oc_day_df = pd.read_csv(file_path)
        except Exception as e:
            LOGGER.warning("Could not read %s: %s", file_path, e)
            continue

        if oc_day_df.empty or "timestamp" not in oc_day_df.columns:
            continue

        oc_day_df["timestamp"] = pd.to_datetime(oc_day_df["timestamp"])
        timestamps = sorted(oc_day_df["timestamp"].unique())
        if len(timestamps) < 5:
            continue

        # Reset agent history per day to avoid cross-day contamination
        if clean_sym in agent.history:
            agent.history[clean_sym].clear()

        # Build chronological snapshot lookups
        snap_map = {ts: oc_day_df[oc_day_df["timestamp"] == ts] for ts in timestamps}
        ts_list = list(timestamps)

        for i, ts in enumerate(ts_list):
            snap = snap_map[ts]
            dt = ts.to_pydatetime()
            spot_price = get_spot_at_time(spot_df, dt, snap)
            if spot_price <= 0:
                continue

            result = agent.process_snapshot(
                symbol=symbol,
                oc_df=snap,
                spot_price=spot_price,
                timestamp=dt,
            )

            if not result or not result.signals:
                continue

            # Evaluate each signal generated
            for sig in result.signals:
                bias = sig.get("bias", "NEUTRAL")
                setup_name = sig.get("setup", "UNKNOWN")

                # Look ahead for outcomes: 15-min, 30-min, 60-min
                fwd_15_spot = None
                fwd_30_spot = None
                fwd_60_spot = None

                for j in range(i + 1, len(ts_list)):
                    future_ts = ts_list[j]
                    elapsed = (future_ts - ts).total_seconds() / 60.0
                    fut_spot = get_spot_at_time(spot_df, future_ts.to_pydatetime(), snap_map[future_ts])
                    if fut_spot > 0:
                        if 12 <= elapsed <= 18 and fwd_15_spot is None:
                            fwd_15_spot = fut_spot
                        elif 25 <= elapsed <= 35 and fwd_30_spot is None:
                            fwd_30_spot = fut_spot
                        elif 55 <= elapsed <= 70 and fwd_60_spot is None:
                            fwd_60_spot = fut_spot

                # If no exact match, fallback to closest available forward snapshot
                if fwd_15_spot is None and (i + 5) < len(ts_list):
                    fwd_15_spot = get_spot_at_time(spot_df, ts_list[i + 5].to_pydatetime(), snap_map[ts_list[i + 5]])
                if fwd_30_spot is None and (i + 10) < len(ts_list):
                    fwd_30_spot = get_spot_at_time(spot_df, ts_list[i + 10].to_pydatetime(), snap_map[ts_list[i + 10]])

                exit_spot = fwd_30_spot or fwd_15_spot or spot_price
                pts_change = exit_spot - spot_price
                pct_change = (pts_change / spot_price) * 100.0

                is_win = (pts_change > 0) if bias == "BULLISH" else (pts_change < 0)
                pnl_pts = pts_change if bias == "BULLISH" else -pts_change

                trades.append({
                    "date": date_str,
                    "timestamp": dt.strftime("%Y-%m-%d %H:%M:%S"),
                    "setup": setup_name,
                    "bias": bias,
                    "entry_spot": spot_price,
                    "exit_spot": exit_spot,
                    "max_pain": result.max_pain,
                    "pcr": result.pcr_oi,
                    "pts_pnl": pnl_pts,
                    "pct_pnl": (pnl_pts / spot_price) * 100.0,
                    "is_win": is_win,
                })

    if not trades:
        LOGGER.warning("No trades generated in backtest.")
        return {}

    tdf = pd.DataFrame(trades)
    total_trades = len(tdf)
    wins = tdf[tdf["is_win"] == True]
    losses = tdf[tdf["is_win"] == False]

    win_rate = (len(wins) / total_trades) * 100.0
    total_pts = float(tdf["pts_pnl"].sum())
    avg_pts = float(tdf["pts_pnl"].mean())

    gross_profit = float(wins["pts_pnl"].sum()) if not wins.empty else 0.0
    gross_loss = abs(float(losses["pts_pnl"].sum())) if not losses.empty else 1.0
    profit_factor = gross_profit / max(gross_loss, 0.01)

    avg_win = float(wins["pts_pnl"].mean()) if not wins.empty else 0.0
    avg_loss = abs(float(losses["pts_pnl"].mean())) if not losses.empty else 0.0

    # Cumulative equity curve & Max Drawdown
    tdf["cum_pts"] = tdf["pts_pnl"].cumsum()
    cum_max = tdf["cum_pts"].cummax()
    drawdown = cum_max - tdf["cum_pts"]
    max_dd = float(drawdown.max())

    # Breakdown by Setup
    setup_summary = []
    for setup, group in tdf.groupby("setup"):
        s_wins = group[group["is_win"] == True]
        s_wr = (len(s_wins) / len(group)) * 100.0
        s_pts = float(group["pts_pnl"].sum())
        s_gp = float(s_wins["pts_pnl"].sum()) if not s_wins.empty else 0.0
        s_gl = abs(float(group[group["is_win"] == False]["pts_pnl"].sum()))
        s_pf = s_gp / max(s_gl, 0.01)
        setup_summary.append({
            "Setup": setup,
            "Trades": len(group),
            "Win Rate %": f"{s_wr:.1f}%",
            "Total PnL (pts)": f"{s_pts:+,.1f}",
            "Profit Factor": f"{s_pf:.2f}",
        })

    results = {
        "symbol": symbol,
        "files_analyzed": len(selected_files),
        "total_trades": total_trades,
        "wins": len(wins),
        "losses": len(losses),
        "win_rate_pct": round(win_rate, 2),
        "total_pts_pnl": round(total_pts, 2),
        "avg_pts_per_trade": round(avg_pts, 2),
        "avg_win_pts": round(avg_win, 2),
        "avg_loss_pts": round(avg_loss, 2),
        "profit_factor": round(profit_factor, 2),
        "max_drawdown_pts": round(max_dd, 2),
        "setup_breakdown": setup_summary,
        "recent_trades": tdf.tail(15).to_dict(orient="records"),
    }

    return results


def print_report(res: Dict[str, Any]) -> None:
    if not res:
        return

    print("\n" + "=" * 75)
    print(f"📊 OPTION CHAIN DATA CHANGE FORENSICS BACKTEST — {res['symbol']}")
    print("=" * 75)
    print(f"• Historical Sessions Analyzed:  {res['files_analyzed']}")
    print(f"• Total Qualified Signals:       {res['total_trades']}")
    print(f"• Winning Trades:                {res['wins']}")
    print(f"• Losing Trades:                 {res['losses']}")
    print(f"• Win Rate:                      {res['win_rate_pct']:.1f}%")
    print(f"• Profit Factor:                 {res['profit_factor']:.2f}")
    print(f"• Total Cumulative Return:       {res['total_pts_pnl']:+,.1f} pts")
    print(f"• Average Expectancy per Trade:  {res['avg_pts_per_trade']:+,.1f} pts")
    print(f"• Average Win / Average Loss:    +{res['avg_win_pts']:,.1f} pts / -{res['avg_loss_pts']:,.1f} pts")
    print(f"• Maximum Drawdown:              {res['max_drawdown_pts']:,.1f} pts")
    print("\n" + "-" * 75)
    print("📈 PERFORMANCE BREAKDOWN BY INSTITUTIONAL SETUP:")
    print("-" * 75)
    print(tabulate(res["setup_breakdown"], headers="keys", tablefmt="fancy_grid"))
    print("=" * 75 + "\n")


if __name__ == "__main__":
    args = parse_args()
    results = run_backtest(symbol=args.symbol, max_files=args.max_files)
    if results:
        print_report(results)
        # Save results
        out_path = Path(args.output_file)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w") as f:
            json.dump(results, f, indent=2)
        LOGGER.info("Saved backtest scorecard to %s", out_path)
