import json
from pathlib import Path

def expand_universe():
    config_path = Path("config/fo_universe.json")
    with open(config_path, "r") as f:
        universe = json.load(f)
        
    additional_fo = {
        "NSE:ADANIENT-EQ": "OIL_GAS",
        "NSE:ADANIPORTS-EQ": "INFRA",
        "NSE:APOLLOTYRE-EQ": "AUTO",
        "NSE:ASHOKLEY-EQ": "AUTO",
        "NSE:ASTRAL-EQ": "CAPITAL_GOODS",
        "NSE:ATUL-EQ": "CHEMICALS",
        "NSE:AUROPHARMA-EQ": "PHARMA",
        "NSE:BALKRISIND-EQ": "AUTO",
        "NSE:BALRAMCHIN-EQ": "SUGAR",
        "NSE:BANDHANBNK-EQ": "BANKING_PVT",
        "NSE:BATAINDIA-EQ": "CONSUMER",
        "NSE:BEL-EQ": "DEFENSE",
        "NSE:BHARATFORG-EQ": "CAPITAL_GOODS",
        "NSE:BHARTIARTL-EQ": "TELECOM",
        "NSE:BHEL-EQ": "POWER",
        "NSE:BIOCON-EQ": "PHARMA",
        "NSE:BSOFT-EQ": "IT",
        "NSE:CANFINHOME-EQ": "FINANCE",
        "NSE:CHAMBLFERT-EQ": "FERTILIZERS",
        "NSE:COFORGE-EQ": "IT",
        "NSE:CONCOR-EQ": "LOGISTICS",
        "NSE:COROMANDEL-EQ": "FERTILIZERS",
        "NSE:CROMPTON-EQ": "CONSUMER",
        "NSE:CUMMINSIND-EQ": "CAPITAL_GOODS",
        "NSE:DEEPAKNTR-EQ": "CHEMICALS",
        "NSE:DELTACORP-EQ": "HOSPITALITY",
        "NSE:DIXON-EQ": "CONSUMER",
        "NSE:ESCORTS-EQ": "AUTO",
        "NSE:EXIDEIND-EQ": "AUTO",
        "NSE:FEDERALBNK-EQ": "BANKING_PVT",
        "NSE:GLENMARK-EQ": "PHARMA",
        "NSE:GMRINFRA-EQ": "INFRA",
        "NSE:GNFC-EQ": "CHEMICALS",
        "NSE:GODREJCP-EQ": "FMCG",
        "NSE:GODREJPROP-EQ": "REALTY",
        "NSE:GRANULES-EQ": "PHARMA",
        "NSE:GUJGASLTD-EQ": "OIL_GAS",
        "NSE:HAVELLS-EQ": "CONSUMER",
        "NSE:HINDCOPPER-EQ": "METALS",
        "NSE:ICICIGI-EQ": "FINANCE",
        "NSE:ICICIPRULI-EQ": "FINANCE",
        "NSE:IDFC-EQ": "FINANCE",
        "NSE:IDFCFIRSTB-EQ": "BANKING_PVT",
        "NSE:IEX-EQ": "EXCHANGE",
        "NSE:IGL-EQ": "OIL_GAS",
        "NSE:INDHOTEL-EQ": "HOSPITALITY",
        "NSE:INDIACEM-EQ": "CEMENT",
        "NSE:INDIAMART-EQ": "IT",
        "NSE:INDIGO-EQ": "AVIATION",
        "NSE:INDUSINDBK-EQ": "BANKING_PVT",
        "NSE:INDUSTOWER-EQ": "TELECOM",
        "NSE:INFY-EQ": "IT",
        "NSE:IPCALAB-EQ": "PHARMA",
        "NSE:IRCTC-EQ": "HOSPITALITY",
        "NSE:JKCEMENT-EQ": "CEMENT",
        "NSE:JSWSTEEL-EQ": "METALS",
        "NSE:JUBLFOOD-EQ": "FMCG",
        "NSE:KOTAKBANK-EQ": "BANKING_PVT",
        "NSE:L&TFH-EQ": "FINANCE",
        "NSE:LALPATHLAB-EQ": "HEALTHCARE",
        "NSE:LAURUSLABS-EQ": "PHARMA",
        "NSE:LICHSGFIN-EQ": "FINANCE",
        "NSE:LT-EQ": "INFRA",
        "NSE:LTIM-EQ": "IT",
        "NSE:LTTS-EQ": "IT",
        "NSE:LUPIN-EQ": "PHARMA",
        "NSE:M&M-EQ": "AUTO",
        "NSE:M&MFIN-EQ": "FINANCE",
        "NSE:MANAPPURAM-EQ": "FINANCE",
        "NSE:MARICO-EQ": "FMCG",
        "NSE:MARUTI-EQ": "AUTO",
        "NSE:MCDOWELL-N-EQ": "BEVERAGES",
        "NSE:MCX-EQ": "EXCHANGE",
        "NSE:METROPOLIS-EQ": "HEALTHCARE",
        "NSE:MFSL-EQ": "FINANCE",
        "NSE:MGL-EQ": "OIL_GAS",
        "NSE:MOTHERSON-EQ": "AUTO",
        "NSE:MPHASIS-EQ": "IT",
        "NSE:MRF-EQ": "AUTO",
        "NSE:MUTHOOTFIN-EQ": "FINANCE",
        "NSE:NATIONALUM-EQ": "METALS",
        "NSE:NAUKRI-EQ": "IT",
        "NSE:NAVINFLUOR-EQ": "CHEMICALS",
        "NSE:NESTLEIND-EQ": "FMCG",
        "NSE:NMDC-EQ": "METALS",
        "NSE:NTPC-EQ": "POWER",
        "NSE:OBEROIRLTY-EQ": "REALTY",
        "NSE:OFSS-EQ": "IT",
        "NSE:ONGC-EQ": "OIL_GAS",
        "NSE:PAGEIND-EQ": "CONSUMER",
        "NSE:PEL-EQ": "FINANCE",
        "NSE:PERSISTENT-EQ": "IT",
        "NSE:PETRONET-EQ": "OIL_GAS",
        "NSE:PFC-EQ": "FINANCE",
        "NSE:PIDILITIND-EQ": "CHEMICALS",
        "NSE:PIIND-EQ": "CHEMICALS",
        "NSE:PNB-EQ": "BANKING_PSU",
        "NSE:POLYCAB-EQ": "CAPITAL_GOODS",
        "NSE:POWERGRID-EQ": "POWER",
        "NSE:PVRINOX-EQ": "ENTERTAINMENT",
        "NSE:RAMCOCEM-EQ": "CEMENT",
        "NSE:RBLBANK-EQ": "BANKING_PVT",
        "NSE:RECLTD-EQ": "FINANCE",
        "NSE:RELIANCE-EQ": "OIL_GAS",
        "NSE:SAIL-EQ": "METALS",
        "NSE:SBICARD-EQ": "FINANCE",
        "NSE:SBILIFE-EQ": "FINANCE",
        "NSE:SBIN-EQ": "BANKING_PSU",
        "NSE:SHREECEM-EQ": "CEMENT",
        "NSE:SIEMENS-EQ": "CAPITAL_GOODS",
        "NSE:SRF-EQ": "CHEMICALS",
        "NSE:SUNPHARMA-EQ": "PHARMA",
        "NSE:SUNTV-EQ": "ENTERTAINMENT",
        "NSE:SYNGENE-EQ": "PHARMA",
        "NSE:TATACHEM-EQ": "CHEMICALS",
        "NSE:TATACOMM-EQ": "TELECOM",
        "NSE:TATACONSUM-EQ": "FMCG",
        "NSE:TATAELXSI-EQ": "IT",
        "NSE:TATAMOTORS-EQ": "AUTO",
        "NSE:TATAPOWER-EQ": "POWER",
        "NSE:TATASTEEL-EQ": "METALS",
        "NSE:TCS-EQ": "IT",
        "NSE:TECHM-EQ": "IT",
        "NSE:TITAN-EQ": "CONSUMER",
        "NSE:TORNTPHARM-EQ": "PHARMA",
        "NSE:TRENT-EQ": "CONSUMER",
        "NSE:TVSMOTOR-EQ": "AUTO",
        "NSE:UBL-EQ": "BEVERAGES",
        "NSE:ULTRACEMCO-EQ": "CEMENT",
        "NSE:UPL-EQ": "CHEMICALS",
        "NSE:VEDL-EQ": "METALS",
        "NSE:VOLTAS-EQ": "CONSUMER",
        "NSE:WIPRO-EQ": "IT",
        "NSE:ZEEL-EQ": "ENTERTAINMENT",
        "NSE:ZYDUSLIFE-EQ": "PHARMA",
        "NSE:BSOFT-EQ": "IT",
        "NSE:COFORGE-EQ": "IT",
        "NSE:PERSISTENT-EQ": "IT",
        "NSE:KPITTECH-EQ": "IT",
        "NSE:SAMMAANCAP-EQ": "FINANCE",
        "NSE:GNFC-EQ": "CHEMICALS",
        "NSE:RCF-EQ": "FERTILIZERS",
        "NSE:FACT-EQ": "FERTILIZERS"
    }
    
    universe.update(additional_fo)
    
    with open(config_path, "w") as f:
        json.dump(universe, f, indent=4)
    
    print(f"Updated F&O universe to {len(universe)} stocks.")

if __name__ == "__main__":
    expand_universe()
