"""
BaseAutonomousAgent — Standardized Agentic AI Protocol for autonomous market observation, reasoning, and action.
"""
from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

from trade_system.domains.market_data.infrastructure.database.connection import get_engine
from trade_system.domains.market_data.infrastructure.database.repository import log_agent_thought
from trade_system.shared.exceptions import AgentDecisionError
from sqlalchemy.orm import Session

LOGGER = logging.getLogger("AutonomousAgent")


@dataclass
class ThoughtProcess:
    """Structured reasoning step generated by an autonomous agent."""
    agent_name: str
    thought_summary: str
    symbol: Optional[str] = None
    action_intent: Optional[str] = None
    confidence: float = 1.0
    evidence: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class AgentAction:
    """Concrete actionable output from agent deliberation."""
    agent_name: str
    action_type: str  # "TRADE_SIGNAL", "WATCHLIST_ADD", "RISK_VETO", "NO_OP"
    payload: Dict[str, Any] = field(default_factory=dict)
    rationale: str = ""
    timestamp: datetime = field(default_factory=datetime.now)


class BaseAutonomousAgent(ABC):
    """
    Standardized Base Autonomous Agent supporting Perception -> Reasoning -> Action -> Reflection loop.
    """

    def __init__(self, name: str, broker: Any = None) -> None:
        self.name = name
        self.broker = broker
        self.engine = get_engine()
        self._last_thought: Optional[ThoughtProcess] = None

    def log_thought(self, message: str, symbol: Optional[str] = None, action: Optional[str] = None) -> None:
        """Persist structured thought to SQLite agent_thoughts audit log."""
        LOGGER.info("[%s] %s", self.name, message)
        try:
            with Session(self.engine) as session:
                log_agent_thought(session, self.name, message, symbol, action)
        except Exception as exc:
            LOGGER.debug("Failed to log thought to DB: %s", exc)

    @abstractmethod
    def observe(self, market_context: Any) -> None:
        """Perception phase: ingest market context, indicators, news, and price structure."""
        pass

    @abstractmethod
    def reason(self) -> ThoughtProcess:
        """Reasoning phase: deliberate, synthesize multi-factor evidence, and form conviction."""
        pass

    @abstractmethod
    def act(self) -> AgentAction:
        """Action phase: emit validated trade suggestions, watchlist modifications, or risk decisions."""
        pass

    def reflect(self, trade_outcome: Dict[str, Any]) -> None:
        """Reflection / Reinforcement phase: evaluate outcome to adjust agent weights."""
        pass
