import sys
import os
import pandas as pd
from datetime import datetime, date
from pathlib import Path

# Add src to path
sys.path.append(str(Path("src").resolve()))

from trade_system.config.settings import Settings
from trade_system.infrastructure.notifications.telegram import TelegramNotifier
from trade_system.infrastructure.database.connection import get_engine

def main():
    print("🔋 Calculating Top Gainers from Database for today...")
    settings = Settings.load()
    
    # Initialize Telegram Notifier for Top Gainers
    bot_token = settings.top_gainer_telegram.bot_token or settings.telegram.bot_token
    chat_id = settings.top_gainer_telegram.chat_id or settings.telegram.chat_id
    
    if not bot_token or not chat_id:
        print("❌ Telegram credentials are not configured in settings or .env!")
        return
        
    notifier = TelegramNotifier(bot_token, chat_id)
    engine = get_engine()
    
    today_str = "2026-05-27"
    
    with engine.connect() as conn:
        # 1. Fetch all data for today
        print("   Loading today's 15m price data...")
        df_today = pd.read_sql("""
            SELECT symbol, timestamp, open, high, low, close, volume 
            FROM ohlcv_15m 
            WHERE date(timestamp) = :date_str
            ORDER BY timestamp ASC
        """, conn, params={"date_str": today_str})
        
        if df_today.empty:
            print(f"❌ No price data found in database for date {today_str}!")
            return
            
        # 2. Fetch last close of previous days for these symbols
        print("   Loading previous day closes...")
        df_prev = pd.read_sql("""
            SELECT symbol, timestamp, close 
            FROM ohlcv_15m 
            WHERE date(timestamp) < :date_str
            ORDER BY timestamp DESC
        """, conn, params={"date_str": today_str})
        
    # Group today's data to calculate latest close, first open, and total volume
    grouped_today = df_today.groupby("symbol")
    stats = []
    
    # Group previous data to get the latest close before today
    prev_closes = {}
    if not df_prev.empty:
        # Since it is sorted descending by timestamp, the first entry per symbol is the latest previous close
        prev_closes = df_prev.groupby("symbol").first()["close"].to_dict()
        
    for symbol, group in grouped_today:
        first_row = group.iloc[0]
        last_row = group.iloc[-1]
        
        # Calculate stats
        today_open = first_row["open"]
        today_close = last_row["close"]
        total_volume = group["volume"].sum()
        
        # Use previous day close if available, fallback to today's open
        prev_close = prev_closes.get(symbol, today_open)
        
        if prev_close <= 0:
            continue
            
        change_pct = ((today_close - prev_close) / prev_close) * 100
        change_val = today_close - prev_close
        
        # Apply standard filters (min price, min volume)
        if today_close < 10.0 or today_close > 50000.0:
            continue
        if total_volume < 20000: # Lower volume filter slightly since it's 15m aggregated
            continue
            
        stats.append({
            "symbol": symbol,
            "name": symbol.replace("NSE:", "").replace("-EQ", ""),
            "close": today_close,
            "change_pct": change_pct,
            "change": change_val,
            "volume": int(total_volume)
        })
        
    if not stats:
        print("❌ No stocks passed the filters!")
        return
        
    df_results = pd.DataFrame(stats)
    # Sort by change percent descending
    df_results = df_results.sort_values("change_pct", ascending=False)
    
    top_10 = df_results.head(10)
    
    # Format Telegram Message
    today_formatted = datetime.strptime(today_str, "%Y-%m-%d").strftime("%d %b %Y")
    lines = [
        f"🏆 <b>Post-Market Top 10 Gainers</b> ({today_formatted})",
        f"<i>Computed offline from Database (Total analyzed: {len(df_results)})</i>",
        "",
    ]
    
    for rank, (_, row) in enumerate(top_10.iterrows(), 1):
        lines.append(f"{rank:02d}. <b>{row['name']}</b>  ₹{row['close']:.2f}  (<code>{row['change_pct']:+.2f}%</code>)")
        
    lines.append("\n<i>Generated by AI Post-Market Agent (Database Fallback)</i>")
    message = "\n".join(lines)
    
    print("\nReport content:")
    print(message)
    
    # Send report
    print("\n   Sending to Telegram...")
    success = notifier.send(message)
    if success:
        print("✅ Telegram report sent successfully!")
        
        # Write Lock file to prevent duplicate runs
        lock_dir = Path("data/top_gainers")
        lock_dir.mkdir(parents=True, exist_ok=True)
        lock_file = lock_dir / f"sent_lock_{today_str.replace('-', '')}.txt"
        lock_file.write_text(f"Sent offline from database at {datetime.now().isoformat()}")
    else:
        print("❌ Failed to send Telegram message.")

if __name__ == "__main__":
    main()
