"""
Midday Coil & Breakout Radar Engine (Afternoon Session Acceleration)
===================================================================
Identifies F&O stocks that:
1. Coiled in a tight volatility squeeze (Range <= 1.0% of price) during the lunch lull (10:30 AM - 12:45 PM).
2. Are breaking out of the midday consolidation range in the afternoon session (1:00 PM - 3:15 PM).
3. Confirm with Relative Volume expansion (RVol >= 1.5x) and Session VWAP alignment.

Surfaces high-probability afternoon runners for traders starting in the middle of the day.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import time as dt_time, datetime
from typing import Any, Dict, List, Optional, Tuple
import numpy as np
import pandas as pd

LOGGER = logging.getLogger(__name__)


@dataclass
class MiddayBreakoutSetup:
    """Actionable trade setup generated by Midday Consolidation Breakout analysis."""
    symbol: str
    sector: str
    ltp: float
    status: str                   # "BULLISH_BREAKOUT", "BEARISH_BREAKDOWN", "COILED_SQUEEZE"
    midday_range_pct: float       # ((High - Low) / Low) * 100 during 10:30-12:45
    midday_high: float            # Ceiling of consolidation
    midday_low: float             # Floor of consolidation
    midday_midpoint: float        # 50% equilibrium of consolidation
    breakout_pct: float           # % distance beyond the consolidation boundary
    vol_surge: float              # Relative volume on breakout candle
    vwap: Optional[float]
    vwap_status: str              # "ABOVE_VWAP", "BELOW_VWAP", "AT_VWAP"
    pcr: Optional[float]
    score: int                    # 0 - 100 composite institutional conviction score
    entry_price: float
    stop_loss: float              # Invalidation level (Midday midpoint)
    target_1: float               # 1:1.8 RRR Target
    target_2: float               # 1:3.0 RRR Extension Target
    risk_reward: float
    catalyst: str
    rationale: List[str] = field(default_factory=list)

    def format_summary(self) -> str:
        icon = "🟢" if "BULLISH" in self.status else ("🔴" if "BEARISH" in self.status else "⚡")
        sym_short = self.symbol.replace("NSE:", "").replace("-EQ", "").replace("-INDEX", "")
        return (
            f"{icon} <b>{sym_short}</b> | <b>{self.status}</b> (Score: {self.score}/100)\n"
            f"   Lunch Coil Range: {self.midday_range_pct:.2f}% (₹{self.midday_low:.2f} - ₹{self.midday_high:.2f})\n"
            f"   Entry: ₹{self.entry_price:.2f} | SL: ₹{self.stop_loss:.2f} | T1: ₹{self.target_1:.2f} (RRR: 1:{self.risk_reward:.1f})\n"
            f"   Catalyst: {self.catalyst}"
        )


class MiddayBreakoutEngine:
    """
    Scans intraday 15m candles to detect Midday Compression and Afternoon Breakouts.
    """

    DEFAULT_COIL_START = dt_time(10, 30)
    DEFAULT_COIL_END = dt_time(12, 45)

    @classmethod
    def evaluate_symbol(
        cls,
        symbol: str,
        sector: str,
        candles_df: pd.DataFrame,
        live_ltp: Optional[float] = None,
        live_volume: Optional[float] = None,
        pcr_value: Optional[float] = None,
        max_coil_pct: float = 1.2,
        min_vol_surge: float = 1.3,
        coil_start: dt_time = DEFAULT_COIL_START,
        coil_end: dt_time = DEFAULT_COIL_END,
    ) -> Optional[MiddayBreakoutSetup]:
        """
        Evaluates a single stock's intraday bars for midday compression and subsequent breakout.
        """
        if candles_df.empty or len(candles_df) < 5:
            return None

        df = candles_df.copy().sort_values("timestamp").reset_index(drop=True)
        if not pd.api.types.is_datetime64_any_dtype(df["timestamp"]):
            df["timestamp"] = pd.to_datetime(df["timestamp"], format="mixed", errors="coerce")

        df["time"] = df["timestamp"].dt.time

        # 1. Extract Midday Consolidation Window (10:30 AM to 12:45 PM)
        coil_mask = (df["time"] >= coil_start) & (df["time"] <= coil_end)
        coil_bars = df[coil_mask]

        if coil_bars.empty or len(coil_bars) < 2:
            return None

        midday_high = float(coil_bars["high"].max())
        midday_low = float(coil_bars["low"].min())
        if midday_low <= 0:
            return None

        midday_range_pct = ((midday_high - midday_low) / midday_low) * 100.0
        midday_midpoint = (midday_high + midday_low) / 2.0

        # Must have coiled within the maximum threshold
        if midday_range_pct > max_coil_pct:
            return None

        # 2. Determine Current Price & Latest Bar
        last_bar = df.iloc[-1]
        current_price = live_ltp if (live_ltp is not None and live_ltp > 0) else float(last_bar["close"])

        # Calculate session VWAP
        vol_sum = df["volume"].sum()
        vwap = float((df["close"] * df["volume"]).sum() / vol_sum) if vol_sum > 0 else None
        vwap_status = "ABOVE_VWAP" if (vwap and current_price >= vwap) else "BELOW_VWAP"

        # Calculate volume surge on the breakout/current bar
        avg_bar_vol = float(df["volume"].mean()) if len(df) > 0 else 1.0
        bar_vol = live_volume if (live_volume is not None and live_volume > 0) else float(last_bar["volume"])
        vol_surge = round(bar_vol / avg_bar_vol, 2) if avg_bar_vol > 0 else 1.0

        # 3. Classify Breakout Direction
        breakout_pct = 0.0
        status = "COILED_SQUEEZE"
        rationale: List[str] = []
        score = 50

        # Bullish Breakout: Price crossed above Midday High
        if current_price > midday_high:
            breakout_pct = ((current_price - midday_high) / midday_high) * 100.0
            status = "BULLISH_BREAKOUT"
            score += 25
            rationale.append(f"Broken out above 10:30-12:45 lunch ceiling (₹{midday_high:.2f}) by +{breakout_pct:.2f}%")
            if vwap and current_price >= vwap:
                score += 15
                rationale.append("Holding above Session VWAP (Institutional Accumulation)")
            if vol_surge >= min_vol_surge:
                score += 15
                rationale.append(f"Volume Surge {vol_surge:.1f}x vs midday average")
            if pcr_value and pcr_value >= 0.8:
                score += 10
                rationale.append(f"Bullish Option Support (PCR: {pcr_value:.2f})")

            sl = midday_midpoint
            risk = max(current_price - sl, current_price * 0.003)
            t1 = current_price + (risk * 1.8)
            t2 = current_price + (risk * 3.0)
            rrr = (t1 - current_price) / risk if risk > 0 else 1.8
            catalyst = f"Midday range squeeze ({midday_range_pct:.2f}%) resolved upward with {vol_surge:.1f}x volume"

            return MiddayBreakoutSetup(
                symbol=symbol,
                sector=sector,
                ltp=round(current_price, 2),
                status=status,
                midday_range_pct=round(midday_range_pct, 2),
                midday_high=round(midday_high, 2),
                midday_low=round(midday_low, 2),
                midday_midpoint=round(midday_midpoint, 2),
                breakout_pct=round(breakout_pct, 2),
                vol_surge=vol_surge,
                vwap=round(vwap, 2) if vwap else None,
                vwap_status=vwap_status,
                pcr=round(pcr_value, 2) if pcr_value else None,
                score=min(100, score),
                entry_price=round(current_price, 2),
                stop_loss=round(sl, 2),
                target_1=round(t1, 2),
                target_2=round(t2, 2),
                risk_reward=round(rrr, 1),
                catalyst=catalyst,
                rationale=rationale,
            )

        # Bearish Breakdown: Price crossed below Midday Low
        elif current_price < midday_low:
            breakout_pct = ((midday_low - current_price) / midday_low) * 100.0
            status = "BEARISH_BREAKDOWN"
            score += 25
            rationale.append(f"Broken down below 10:30-12:45 lunch floor (₹{midday_low:.2f}) by -{breakout_pct:.2f}%")
            if vwap and current_price <= vwap:
                score += 15
                rationale.append("Holding below Session VWAP (Institutional Distribution)")
            if vol_surge >= min_vol_surge:
                score += 15
                rationale.append(f"Volume Surge {vol_surge:.1f}x vs midday average")
            if pcr_value and pcr_value <= 0.6:
                score += 10
                rationale.append(f"Bearish Option Positioning (PCR: {pcr_value:.2f})")

            sl = midday_midpoint
            risk = max(sl - current_price, current_price * 0.003)
            t1 = current_price - (risk * 1.8)
            t2 = current_price - (risk * 3.0)
            rrr = (current_price - t1) / risk if risk > 0 else 1.8
            catalyst = f"Midday range squeeze ({midday_range_pct:.2f}%) resolved downward with {vol_surge:.1f}x volume"

            return MiddayBreakoutSetup(
                symbol=symbol,
                sector=sector,
                ltp=round(current_price, 2),
                status=status,
                midday_range_pct=round(midday_range_pct, 2),
                midday_high=round(midday_high, 2),
                midday_low=round(midday_low, 2),
                midday_midpoint=round(midday_midpoint, 2),
                breakout_pct=round(breakout_pct, 2),
                vol_surge=vol_surge,
                vwap=round(vwap, 2) if vwap else None,
                vwap_status=vwap_status,
                pcr=round(pcr_value, 2) if pcr_value else None,
                score=min(100, score),
                entry_price=round(current_price, 2),
                stop_loss=round(sl, 2),
                target_1=round(t1, 2),
                target_2=round(t2, 2),
                risk_reward=round(rrr, 1),
                catalyst=catalyst,
                rationale=rationale,
            )

        # Still Coiled Inside Range (Watchlist Candidate about to blast)
        else:
            dist_to_high = ((midday_high - current_price) / current_price) * 100.0
            dist_to_low = ((current_price - midday_low) / current_price) * 100.0
            closer_bound = "Ceiling" if dist_to_high < dist_to_low else "Floor"
            closer_dist = min(dist_to_high, dist_to_low)

            score = 60
            if midday_range_pct <= 0.7:
                score += 15
                rationale.append(f"Ultra-tight volatility coil ({midday_range_pct:.2f}% channel)")
            else:
                rationale.append(f"Tight consolidation box ({midday_range_pct:.2f}% channel)")

            rationale.append(f"Trading inside range; {closer_dist:.2f}% away from {closer_bound}")
            catalyst = f"Coiling in tight {midday_range_pct:.2f}% box between ₹{midday_low:.2f} and ₹{midday_high:.2f}; prime for afternoon expansion"

            return MiddayBreakoutSetup(
                symbol=symbol,
                sector=sector,
                ltp=round(current_price, 2),
                status=status,
                midday_range_pct=round(midday_range_pct, 2),
                midday_high=round(midday_high, 2),
                midday_low=round(midday_low, 2),
                midday_midpoint=round(midday_midpoint, 2),
                breakout_pct=0.0,
                vol_surge=vol_surge,
                vwap=round(vwap, 2) if vwap else None,
                vwap_status=vwap_status,
                pcr=round(pcr_value, 2) if pcr_value else None,
                score=min(100, score),
                entry_price=round(midday_high * 1.001, 2),
                stop_loss=round(midday_midpoint, 2),
                target_1=round(midday_high + (midday_high - midday_midpoint) * 1.8, 2),
                target_2=round(midday_high + (midday_high - midday_midpoint) * 3.0, 2),
                risk_reward=1.8,
                catalyst=catalyst,
                rationale=rationale,
            )

    @classmethod
    def scan_universe(
        cls,
        today_15m_df: pd.DataFrame,
        quotes: Optional[Dict[str, Any]] = None,
        pcr_cache: Optional[Dict[str, Any]] = None,
        fo_metadata: Optional[Dict[str, str]] = None,
        max_coil_pct: float = 1.2,
        min_vol_surge: float = 1.2,
    ) -> List[MiddayBreakoutSetup]:
        """
        Scans the full F&O universe across today's 15m candles to find active breakouts & coiled stocks.
        """
        if today_15m_df.empty:
            return []

        quotes = quotes or {}
        pcr_cache = pcr_cache or {}
        fo_metadata = fo_metadata or {}

        setups: List[MiddayBreakoutSetup] = []
        grouped = today_15m_df.groupby("symbol")

        for symbol, grp in grouped:
            if "INDEX" in symbol:
                continue

            sector = fo_metadata.get(symbol, "UNKNOWN")
            q = quotes.get(symbol)
            live_ltp = float(getattr(q, "last_price", 0.0) or getattr(q, "close", 0.0) or 0.0) if q else None
            live_vol = float(getattr(q, "volume", 0.0) or 0.0) if q else None

            pcr_data = pcr_cache.get(symbol, {})
            pcr_val = float(pcr_data.get("pcr_oi", 0.0)) if pcr_data else None

            setup = cls.evaluate_symbol(
                symbol=symbol,
                sector=sector,
                candles_df=grp,
                live_ltp=live_ltp,
                live_volume=live_vol,
                pcr_value=pcr_val,
                max_coil_pct=max_coil_pct,
                min_vol_surge=min_vol_surge,
            )
            if setup:
                setups.append(setup)

        # Sort: active breakouts first, ordered by conviction score descending
        setups.sort(
            key=lambda s: (
                0 if "BREAKOUT" in s.status or "BREAKDOWN" in s.status else 1,
                -s.score,
                -abs(s.breakout_pct)
            )
        )
        return setups
