"""Core domain layer: events, models, and signals (compatibility mapping)."""

from trade_system.shared.events.bus import EventBus, MarketEvent, SignalEvent
from trade_system.domains.trading.domain.models.domain import (
    MarketData,
    Signal,
    SignalType,
    Trade,
    TradeStatus,
    TradeHorizon,
    TradeDirection,
    TradeOutcome,
    MarketRegime,
    MarketContext,
    OptionChainSnapshot,
    OptionChainAnalysis,
    GlobalContext,
    PreMarketBrief,
    OptionParams,
    SetupFeatures,
    TradeSuggestion,
    SessionPlan,
    VolumeProfileSummary,
)
from trade_system.domains.strategy.domain.signals import SignalGenerator
from trade_system.domains.trading.domain.ports.broker import Broker, DataBroker, TradingBroker
from trade_system.shared.ports.notifier import Notifier
from trade_system.shared.ports.weights import WeightsProvider

from trade_system.shared.exceptions import (
    TradeSystemError,
    BrokerError,
    BrokerAuthError,
    BrokerSessionExpiredError,
    BrokerRateLimitError,
    MarketDataError,
    DataGapError,
    DataSanityError,
    StrategyError,
    NotificationError,
    AgentError,
)

__all__ = [
    "EventBus",
    "MarketEvent",
    "SignalEvent",
    "MarketData",
    "Signal",
    "SignalType",
    "Trade",
    "TradeStatus",
    "TradeHorizon",
    "TradeDirection",
    "TradeOutcome",
    "MarketRegime",
    "MarketContext",
    "OptionChainSnapshot",
    "OptionChainAnalysis",
    "GlobalContext",
    "PreMarketBrief",
    "OptionParams",
    "SetupFeatures",
    "TradeSuggestion",
    "SessionPlan",
    "SignalGenerator",
    "Broker",
    "DataBroker",
    "TradingBroker",
    "Notifier",
    "WeightsProvider",
    "TradeSystemError",
    "BrokerError",
    "BrokerAuthError",
    "BrokerSessionExpiredError",
    "BrokerRateLimitError",
    "MarketDataError",
    "DataGapError",
    "DataSanityError",
    "StrategyError",
    "NotificationError",
    "AgentError",
]
